name: Setup Node and Dependencies
description: Setup Node.js, enable Corepack, and install dependencies

runs:
  using: "composite"
  steps:
    - name: Setup tools (Node, Yarn, Snyk)
      uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
      with:
        install: true

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
