name: Setup Node and Dependencies
description: Setup Node.js, enable Corepack, and install dependencies

runs:
  using: "composite"
  steps:
    - name: Setup tools (Node, Yarn, Snyk)
      uses: jdx/mise-action@v2
      with:
        install: true

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
