name: Setup Bun and Dependencies
description: Setup Bun and install dependencies

runs:
  using: "composite"
  steps:
    - name: Setup tools (Bun, Snyk)
      uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
      with:
        install: true

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
