name: laa-civil-manage

services:
  frontend:
    container_name: frontend
    depends_on: [redis]
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8888:3000"
    environment:
      BASE_URL_MAP: '{"urls":{"default":"http://localhost:3000/mock-data"}}'
      NODE_ENV: production
      AUTH_REDIRECT_URL: http://localhost:8888/auth/redirect
      SESSION_REDIS_URL: redis://redis:6379
      DEPARTMENT_NAME: DEPARTMENT_NAME
      RATE_LIMIT_MAX: 100
      RATE_WINDOW_MS: 900000
      SERVICE_NAME: DOCKER COMPOSE
      SERVICE_PHASE: Alpha
      SESSION_SECRET:
      SESSION_NAME: sessionId
      BACKEND_URL: http://host.docker.internal:8081

  redis:
    container_name: redis
    image: "redis:8.10-alpine@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576"
    ports:
      - "6379:6379"
