[tools]
bun = "latest"
snyk = "1.1302.1" #TODO - do we want to pin the snyk version?

[tasks.install]
description = "Install dependencies"
run = "bun install"

[tasks.dev]
description = "Start development server"
run = "bun run dev"

[tasks.build]
description = "Build the application"
run = "bun run build"

[tasks.lint]
description = "Lint code with eslint"
run = "bun lint"

[tasks.lint_check]
description = "Check code linting with eslint"
run = "bun lint:check"

[tasks.format]
description = "Format code with Prettier"
run = "bun format"

[tasks.format_check]
description = "Check code formatting with Prettier"
run = "bun format:check"


[tasks.test]
description = "Run all tests"
run = "bun test"