[tools]
node = "25.7.0"
snyk = "1.1302.1"
yarn = "4.12.0"

[tasks.install]
description = "Install dependencies"
run = "yarn install"

[tasks.dev]
description = "Start development server"
run = "yarn dev"

[tasks.build]
description = "Build the application"
run = "yarn build"

[tasks.test]
description = "Run all tests"
run = "yarn test"

[tasks.test_unit]
description = "Run unit tests"
run = "yarn test:unit"

[tasks.test_e2e]
description = "Run E2E tests"
run = "yarn test:e2e"

[tasks.lint]
description = "Lint code with eslint"
run = "yarn lint"

[tasks.lint_check]
description = "Check code linting with eslint"
run = "yarn lint:check"

[tasks.format]
description = "Format code with Prettier"
run = "yarn format"

[tasks.format_check]
description = "Check code formatting with Prettier"
run = "yarn format:check"

[tasks.playwright]
description = "Run Playwright acessibility tests"
run = "yarn playwright test"
