services:
  civil-manage:
    build:
      context: ../../../.
      args:
        NODE_ENV: test
    ports:
      - "3000:3000"
    environment:
      SKIP_AUTH: "true"
      SESSION_SECRET: zap-test-secret
      SESSION_NAME: sessionId
      DEPARTMENT_NAME: ZAP_DEPARMENT
      DEPARTMENT_URL: http://fake-zap-url.fake
      AUTH_REDIRECT_URL: http://localhost:3000
      AUTH_CLIENT_SECRET: zap-test-secret
      AUTH_CLIENT_ID: zap-test-secret
      BACKEND_URL: http://wiremock:8080
      SERVICE_NAME: Zap service
      SERVICE_PHASE: Zap Phase
  zap-scan:
    image: zaproxy/zap-stable
    command: zap.sh -cmd -port 9090 -autorun /zap/wrk/zap.yaml
    volumes:
      - ../../../.:/zap/wrk:rw
    links:
      - civil-manage
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ../../infrastructure/wiremock/mappings:/home/wiremock/mappings:ro
    command: --verbose
