name: Check PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

# run-name: ${{ github.actor }} is learning GitHub Actions

# jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v5
#       - uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#       - run: npm install -g bats
#       - run: bats -v




jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.user.login, '[bot]') }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: "^\\[AP-\\d+\\]\\s.*$"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-comment: ":x: Please ensure your PR title matches the format: [AP-XXX] Ticket description"
          on-succeeded-regex-dismiss-review-comment: "PR title check has passed"
