name: Check PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.user.login, '[bot]') }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: "^\\[AD-\\d+\\]\\s.*$"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-comment: ":x: Please ensure your PR title matches the format: [AD-XXX] Ticket description"
          on-succeeded-regex-dismiss-review-comment: "PR title check has passed"
